name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there 👋, it looks like you are new here! Thanks for contributing. Have you checked our contributing guidelines and code of conduct?'
        pr-message: 'Hi there 👋, it looks like you are new here! Have you read the contributing guidelines and code of conduct?'
